name: 'Terravision - S3 Deploy'
description: 'Generates and Deploys Infrastructure Diagrams'
inputs:
  aws-access-key-id:
    description: The Access Key ID for the AWS credential being used to push into the S3 Bucket 
    required: true
  aws-secret-access-key:
    description: The Secret Access Key for the AWS credential being used to push into the S3 Bucket
    required: true
  aws-s3-bucket-base-uri:
    description: The base URI of the S3 bucket to push the terravision artifacts to. There should be no trailing slash (e.g. s3://example-bucket/base/path)
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile' # FIXME we can greatly increase performance by prebuilding our Docker image and pulling that instead of building the image on each action run
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-s3-bucket-base-uri }}